import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { CookiesProvider } from "next-client-cookies/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const googleClientId = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID as string;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GoogleOAuthProvider clientId={googleClientId}>
      <CookiesProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </CookiesProvider>
    </GoogleOAuthProvider>
  );
}
